extern struct Node *NewNode();
extern void FreeNode(struct Node *p);
extern void InitNode(struct Node *n);
extern void InitOFNode(struct OverFlowNode *n);
extern void InitBranch(struct Branch *b);
extern void PrintNode(struct Node *n);
extern void PrintBranch(struct Branch *b);
extern struct Rect NodeCover(struct Node *n);
extern struct Rect MinNodeCover(struct Node *n);
extern struct Rect MinOFNodeCover(struct OverFlowNode *overflow, struct Rect rect);
extern int PickBranch(struct Rect *r, struct Node *n);
extern int AddBranch(int idxp, struct Branch *b, struct Node *n, struct Node **new);
extern void DisconBranch(struct Node *n, int i);
extern int Equal2Rects(struct Rect r1, struct Rect r2);
extern int RectInNode(struct Rect r, struct Node *n);
extern int RectInOFN(struct Rect r, struct OverFlowNode *overflow);
extern int IsOverFlow( struct Rect *n);
extern void SetOverFlow( struct Rect *r);
